frameworkVersion: ">=1.2.0 <2.0.0"

service: upload-service

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  environment:
    SERVERLESS_STAGE: ${opt:stage, self:provider.stage}
    SERVERLESS_PROJECT: ${self:service}
    SERVERLESS_REGION: ${opt:region, self:provider.region}
    CHUNKS_TABLE_NAME: godashpi-${self:provider.environment.SERVERLESS_STAGE}-chunks-table
    UPLOAD_BUCKET_NAME:
      Ref: UploadBucket
  iamRoleStatements:
    - Effect: Allow
      Action:
      - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.environment.SERVERLESS_REGION}:*:*
    - Effect: Allow
      Action:
      - SNS:*
      Resource: arn:aws:sns:${self:provider.environment.SERVERLESS_REGION}:*:*
    - Effect: Allow
      Action:
      - S3:PutObject
      Resource: "*"

package:
  exclude:
    - test/**
    - .git/**

functions:
  register-chunk:
    handler: register-chunk/index.handler
    events:
      - http:
          path: register-chunk
          method: post
          cors: true
    timeout: 20

plugins:
  - serverless-mocha-plugin
  - serverless-webpack
  - serverless-offline

custom:
  serverless-mocha-plugin:
    functionTemplate: templates/function.ejs
  webpackIncludeModules: true

resources:
  Outputs:
    UploadBucket:
      Value:
        Ref: UploadBucket
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: Private
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
            Id: CorsRule1
            MaxAge: '3600'
      DeletionPolicy: Delete
    ChunksTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: session
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: session
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CHUNKS_TABLE_NAME}