'use strict';

// tests for capture-frame
// Generated by serverless-mocha-plugin

const mod = require('../capture-frame/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const putObject = require('./s3put-event.json');

process.env.FFMPEG = 'ffmpeg';

describe('capture-frame', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda
    done();
  });

  it('implement tests here', () => {
    return wrapped.run(putObject).then((response) => {
      console.log('RESPONSE', response);
      expect(response).not.to.be.empty;
    });
  });
});
